### ISSUE TITLE
Infografía - Vásquez Reyes Gibran Jesus

### ISSUE THREAD

**Issue by GibranVasquez** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-GibranVasquez#1]
Librerías de Programación - Infografía
https://drive.google.com/file/d/1d0P8xKtdxCOxXKV3zMDL42ml6syxw6os/view?usp=sharing

**Comment by KevCH24** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
